//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_System_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id_order { get; set; }
        public int id_customer { get; set; }
        public int id_dlivery { get; set; }
        public string item { get; set; }
        public string Payment { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
